stages:
- stage: Apply
  displayName: "Terraform Apply"

  dependsOn: Plan

  jobs:
  - deployment: Apply
    displayName: Terraform Apply

    environment: Production

    pool:
      vmImage: ubuntu-latest

    strategy:
      runOnce:
        deploy:
          steps:

          - checkout: self

          - task: DownloadPipelineArtifact@2
            displayName: Download Terraform Plan
            inputs:
              artifact: terraform-plan
              path: $(Pipeline.Workspace)

          - task: TerraformInstaller@1
            displayName: Install Terraform
            inputs:
              terraformVersion: '1.14.0'

          - task: AzureCLI@2
            displayName: Terraform Apply
            inputs:
              azureSubscription: Azure-Service-Connection
              scriptType: bash
              scriptLocation: inlineScript
              workingDirectory: $(Build.SourcesDirectory)
              inlineScript: |
                terraform init

                ls -R $(Pipeline.Workspace)

                terraform apply -auto-approve $(Pipeline.Workspace)/terraform-plan/tfplan