stages:
- stage: Apply
  displayName: Terraform Apply
  dependsOn: Plan

  jobs:
  - deployment: Apply
    displayName: Terraform Apply
    environment: Production

    pool:
      vmImage: ubuntu-latest

    strategy:
      runOnce:
        deploy:
          steps:

          - checkout: self

          - task: DownloadPipelineArtifact@2
            displayName: Download Terraform Plan
            inputs:
              artifact: tfplan
              path: $(Pipeline.Workspace)

          - task: TerraformInstaller@1
            inputs:
              terraformVersion: '1.14.0'

          - task: AzureCLI@2
            displayName: Terraform Apply
            inputs:
              azureSubscription: Azure-Service-Connection
              scriptType: bash
              scriptLocation: inlineScript
              workingDirectory: $(Build.SourcesDirectory)
              inlineScript: |
                echo "Current Directory"
                pwd

                echo "Pipeline Workspace"
                ls -R $(Pipeline.Workspace)

                terraform init

                terraform apply -auto-approve $(Pipeline.Workspace)/tfplan/tfplan