stages:
- stage: Plan
  displayName: "Terraform Plan"

  dependsOn: Validate

  jobs:
  - job: Plan

    pool:
      vmImage: ubuntu-latest

    steps:

    - checkout: self

    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: '1.14.0'

    - task: AzureCLI@2
      displayName: Terraform Plan
      inputs:
        azureSubscription: Azure-Service-Connection
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          terraform init
          terraform plan -out=tfplan

          mkdir terraform-plan
          mv tfplan terraform-plan/

    - task: PublishPipelineArtifact@1
      displayName: Publish Terraform Plan
      inputs:
        targetPath: terraform-plan
        artifact: terraform-plan