stages:
- stage: Validate
  displayName: "Terraform Validate"

  jobs:
  - job: Validate

    pool:
      vmImage: ubuntu-latest

    steps:

    - checkout: self

    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: '1.14.0'

    - script: terraform version
      displayName: Terraform Version

    - script: terraform fmt -check -recursive
      displayName: Terraform Format Check

    - task: AzureCLI@2
      displayName: Terraform Init
      inputs:
        azureSubscription: Azure-Service-Connection
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          terraform init

    - task: AzureCLI@2
      displayName: Terraform Validate
      inputs:
        azureSubscription: Azure-Service-Connection
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          terraform validate